@kpiotr6
laserchess/typescript-chess-engine pull request #1
Opened 2023-07-15 19:06 UTC by kpiotr6

Adding vectors and their tests.

2023-07-15 21:39 UTC, Szaroslav commented
Prettified the code; added semicolons and multi-line imports/exports of bigger objects :)

You need to change imports/exports from `.js` to `.ts` extensions, we may to update `tsconfig.json` or `package.json` (don't remember) to avoid including these extensions constantly. Also, add 120 width rule in _VSCode_ and adjust vector test module to it.
1. CTRL + Shift + P (open command palette).
2. Type **Open user settings** and open JSON file.
3. Add new property:
```json
"editor.rulers": [ 120 ]
```
<br>

You accidentally remove at least 2 lines from `package.json` - `dev` and `build` scripts.

2023-07-15 21:41 UTC, Szaroslav requested changes
Prettified the code; added semicolons and multi-line imports/exports of bigger objects :)

You need to change imports/exports from `.js` to `.ts` extensions, we may to update `tsconfig.json` or `package.json` (don't remember) to avoid including these extensions constantly. Also, add 120 width rule in _VSCode_ and adjust vector test module to it.
1. CTRL + Shift + P (open command palette).
2. Type **Open user settings** and open JSON file.
3. Add new property:
```json
"editor.rulers": [ 120 ]
```
<br>

You accidentally remove at least 2 lines from `package.json` - `dev` and `build` scripts.

2023-07-15 21:42 UTC, Szaroslav commented
I will check the geometry module and its tests later, but looks good.

2023-07-16 08:40 UTC, Szaroslav commented on tests/utils/vector.test.ts
Wrong directory.

2023-07-16 16:19 UTC, Szaroslav requested changes

2023-07-16 16:19 UTC, Szaroslav commented on src/geometry/vector2d.ts
> +  }
For new we don't need getters, also TypeScript offers explicit getters and setters: [TypeScript getters/setters](https://www.typescriptlang.org/docs/handbook/2/classes.html#getters--setters).

2023-07-16 16:19 UTC, Szaroslav commented on src/geometry/vector2d.ts
> +  }
I would swap this method position with `constructor`.

2023-07-16 16:19 UTC, Szaroslav commented on src/geometry/vector2d.ts
> +    let board: BoardVector2d = vector as BoardVector2d
Wrong variable name, it's very confusing.

2023-07-16 16:19 UTC, Szaroslav commented on src/geometry/vector2d.ts
> +export class IntVector2d extends Vector2d {
Need to hide `int` implementation due continuous type casting.

2023-07-16 16:19 UTC, Szaroslav commented on tests/geometry/vector.test.ts
> +    expect(()=>{
Spaces :) `expect(() => {`

2023-07-16 16:19 UTC, Szaroslav commented on src/geometry/vector2d.ts
> +      }
Should split the condition into separate dimensions for the clarity of exception. Also, add space after `if` keyword and closing bracket.

2023-07-16 16:19 UTC, Szaroslav commented on src/geometry/vector2d.ts
> +    if(other == 0){
Add space after `if` keyword and closing bracket.

2023-07-16 16:19 UTC, Szaroslav commented on tests/geometry/vector.test.ts
> +});
Should test also edge cases, when these vectors aren't constructed by integer numbers.

2023-07-18 18:08 UTC, Szaroslav requested changes
Keep going, keep grinding. All eyes on you.

2023-07-19 14:55 UTC, kpiotr6 commented on src/geometry/vector2d.ts
> +    if (other == 0) {
Yeah. Don't remind me xd.

2023-07-19 19:06 UTC, Szaroslav commented on src/pieces/direction.ts
Understood xd

2023-07-20 17:23 UTC, Szaroslav approved these changes
Some changes need to be applied but I closing this pull request. Need to open a new one with part of the game logic.

2023-07-20 17:24 UTC, merged